services:
  - type: web
    name: alijaxon
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python manage.py makemigrations && python manage.py migrate && gunicorn root.wsgi:application"


