# Generated by Django 5.2 on 2025-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
